<input type="button" onclick="location.href='A_phptest03.php'"   value="ステータス"><br><br>
<input type="button" onclick="location.href='A_phptest04_1.php'" value="投稿"><br><br>
<input type="button" onclick="location.href='A_phptest05_1.php'" value="じぶんの投稿"><br><br>
<input type="button" onclick="location.href='A_phptest06_1.php'" value="新規登録"><br><br>
<input type="button" onclick="location.href='A_phptest07_1.php'" value="新規登録"><br><br>
<input type="button" onclick="location.href='A_phptest08_1.php'" value="新規登録"><br><br>
<input type="button" onclick="location.href='A_phptest09_1.php'" value="新規登録"><br><br>
<input type="button" onclick="location.href='A_phptest10_1.php'" value="新規登録"><br><br>
<input type="button" onclick="location.href='A_phptest11_1.php'" value="新規登録"><br><br>
<input type="button" onclick="location.href='A_phptest12_1.php'" value="新規登録"><br><br>